version: '3.8'

services:
  fashion_chat:
    image: fashion_chat:v1
    runtime: nvidia
    env_file: .env
    container_name: fashion_chat
    volumes:
      - ./image:/workspace/image
    ports:
      - 54063:8080
    expose:
      - 80
      - 8080
      - 8888
    restart: "always"

  openai_hub:
    image: openai_hub:v1
    env_file: .env
    container_name: openai_hub
    volumes:
      - ./image:/workspace/image
    ports:
      - 80:80
    expose:
      - 80
    restart: "always"

  virtual_tryon:
    image: virtual_tryon:v1
    env_file: .env
    container_name: virtual_tryon
    runtime: nvidia
    volumes:
      - ./ckpts:/workspace/ckpts
      - ./image:/workspace/image
    ports:
      - 8888:8888
    expose:
      - 8888
    restart: "always"