from .background_removing import BackgroundRemoving
from .cannytext2image import CannyText2Image
from .dalle_generate import DalleGenerate
from .dalle_inpainting import DalleInpainting
from .depthtext2image import DepthText2Image
from .hedtext2image import HedText2Image
from .image_captioning import ImageCaptioning
from .image_editing import ImageEditing
from .image2canny import Image2Canny
from .image2depth import Image2Depth
from .image2hed import Image2Hed
from .image2line import Image2Line
from .image2normal import Image2Normal
from .image2pose import Image2Pose
from .image2scribble import Image2Scribble
from .infinity_outpainting import InfinityOutPainting
from .inpainting import Inpainting
from .instruct_pix2pix import InstructPix2Pix
from .linetext2image import LineText2Image
from .normaltext2image import NormalText2Image
from .object_segmenting import ObjectSegmenting
from .posetext2image import PoseText2Image
from .scribbletext2image import ScribbleText2Image
from .sd_inpainting import SDInpainting
from .sdvideo import SDVideo
from .segmenting import Segmenting
from .text2box import Text2Box
from .text2image import Text2Image
from .virtual_tryon import VirtualTryon
from .visual_question_answering import VisualQuestionAnswering
